/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Mohamed Ibrahim
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "../../MCAL/ICU/icu.h"
#include <avr/delay.h>


/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
static volatile uint8 g_edgeCounter = 0; 	/* To recored the high pulse and low pulse counts */
static volatile uint16 g_highPulseTime = 0;	/* To store the ECHO HIGH pulse time generate by UTLRASONIC */

/* Adjust ICU configuration required for the Ultrasonic */
static Icu_ConfigType ultrasonicICUConfig = {.clock = ULTRASONIC_ICU_CONFIG_CLOCK, .edge = RISING};

/* Flag to indicate that the full high pulse is capture by ICU */
static uint8 g_isOutputReady = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Function to initialize the ICU driver
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Initialize ICU as required */
	Icu_init(&ultrasonicICUConfig);

	/* Set ICU ISR to the ultrasonic edge processing function */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Set ultrasonic trigger pin to output */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);

}
/*
 * Description: Function to Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/* Send a high pulse with minimum 10 micro-seconds width */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
	_delay_ms(1);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);

}
/*
 * Description: - Function to send the trigger pulse by using Ultrasonic_Trigger function.
 * 				- Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	/* Send Trigger pulse */
	Ultrasonic_Trigger();

	/* wait for output to be ready */
	while (!g_isOutputReady);

	/* reset g_isOutputReady flag to 0 */
	g_isOutputReady = 0;

	/* return distance */
	return (g_highPulseTime / 58.8);
}
/*
 * Description: This is the call back function called by the ICU driver.
 *              This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	/* increment edge counter with every ICU interrupt */
	g_edgeCounter++;


	if(1 == g_edgeCounter) /* captured high edge generated by ECHO pin */
	{
		/* Reset timer counter */
		Icu_clearTimerValue();

		/* wait for the low edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(2 == g_edgeCounter) /* captured the low pulse */
	{
		/* get the input capture value */
		g_highPulseTime = Icu_getInputCaptureValue();

		/* set the output ready flag */
		g_isOutputReady = 1;

		/* reset edge counter to zero */
		g_edgeCounter = 0;

		/* reset ICU detection to rising edge */
		Icu_setEdgeDetectionType(RISING);

	}


}
