 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the Ultrasonic driver
 *
 * Author: Mohamed Ibrahim
 *
 *******************************************************************************/

/*
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
*/
#pragma once

#include "../../std_types.h"
#include "../../MCAL/GPIO/gpio.h"

/*******************************************************************************
 *                         Types Declaration                                   *
 *******************************************************************************/
#define ULTRASONIC_TRIGGER_PORT			PORTB_ID
#define ULTRASONIC_TRIGGER_PIN			PIN5_ID


#define ULTRASONIC_ECHO_PORT			PORTD_ID
#define ULTRASONIC_ECHO_PIN				PIN6_ID

#define ULTRASONIC_ICU_CONFIG_CLOCK 	F_CPU_8
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description : Function to initialize the ICU driver
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);
/*
 * Description: Function to Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);
/*
 * Description: - Function to send the trigger pulse by using Ultrasonic_Trigger function.
 * 				- Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description: This is the call back function called by the ICU driver.
 *              This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


//#endif /* ULTRASONIC_H_ */
